# Generated by Django 2.0.5 on 2018-11-18 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('moblie_no', models.IntegerField(null=True)),
                ('address', models.TextField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('des', models.TextField(max_length=200)),
                ('abanding_flag', models.IntegerField(default=1)),
            ],
        ),
    ]
