# Generated by Django 2.0.5 on 2018-11-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='des',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='moblie_no',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
