# Generated by Django 2.0.5 on 2018-11-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20181118_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='moblie_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
