# Generated by Django 2.0.5 on 2018-12-09 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20181206_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=50)),
                ('abandon_flag', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=20, null=True)),
                ('updated_by', models.CharField(max_length=20, null=True)),
                ('descriptions', models.TextField(max_length=200, null=True)),
            ],
        ),
    ]
